[pytest]
markers =
    smoke: marker for smoke tests
    regression: marker for regression tests
    win10
    register: tests for user registration
    need_review: test for review



# # Инверсия
# Чтобы запустить все тесты, не имеющие заданную маркировку, можно использовать инверсию. Для запуска всех тестов,
# не отмеченных как smoke, нужно выполнить команду:
# pytest -s -v -m "not smoke" test_fixture8.py
#
#
# Объединение тестов с разными маркировками
# Для запуска тестов с разными метками можно использовать логическое ИЛИ. Запустим smoke и regression-тесты:
# pytest -s -v -m "smoke or regression" test_fixture8.py


# Чтобы запустить только smoke-тесты для Windows 10, нужно использовать логическое И:
# pytest -s -v -m "smoke and win10" test_fixture81.py