[pytest]
markers =
    smoke: marker for smoke tests
    regression: marker for regression tests
    win10
    register: tests for user registration
    need_review: test for review
    login_guest: test for login


